### ISSUE TITLE
parse method is broken

### ISSUE THREAD

**Issue by niieani** [anodynos/upath#4]
running this causes an error:
```ts
> upath.parse('/a/b.html')
```

```
TypeError: p.replace is not a function
    at toUnix (node_modules/upath/build/code/upath.js:30:9)
    at Object.parse (node_modules/upath/build/code/upath.js:51:16)
    at repl:1:7
    at REPLServer.defaultEval (repl.js:272:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:441:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
    at REPLServer.Interface._onLine (readline.js:224:10)
```

While node's `path` works propertly:

```js
> path.parse('/a/b.html')
{ root: '/', dir: '/a', base: 'b.html', ext: '.html', name: 'b' }
```

**Comment by anodynos** [comment]
Sorry for delaying this answer - I will look into it this weekend

**Comment by niieani** [comment]
Cool, no hurry. We've worked around the issue by not using `parse` at all :)

**Comment by niieani** [comment]
Thanks!

**Comment by anodynos** [comment]
Just give me love (and a git star :-)
